#!/bin/bash

if [ -z "$1" ]; then
    echo "Missing argument for: pod name."
	echo "Use --help for more information."
else
    if [ "$1" == "--help" ]; then
        echo -e "\nRuns bundle exec pod update."
        echo -e "Usage: bpdu [--help] <pod_name>\n"
    else
        bundle exec pod update "$1"
    fi
fi
