#!/bin/bash

if [ -z "$1" ]; then
    echo "Missing argument for: target branch."
    echo "Use --help for more information."
else
    if [ "$1" == "--help" ]; then
        echo -e "\nLocally updates the informed branch and rebases your current branch based on the updated branch."
		echo -e "\nUsage: grb [--help] <target_branch>.\n"
    else
        CURR="$(git symbolic-ref --short HEAD)"
        TRGT="$1"

        if [ -z "$CURR" ]; then
            echo "Impossible to rebase."
        else
            git checkout "$TRGT"
            git pull
            git checkout "$CURR"
            git rebase -i "$TRGT"
        fi

        unset CURR
        unset TRGT
    fi
fi
