#!/bin/bash

if [ -z "$1" ]; then
    echo "Missing argument for: reset mode."
    echo "Use --help for more information."
else
    if [ "$1" == "--help" ]; then
        echo -e "\nResets the current branch to some state, according to defined mode."
        echo "Usage: grs [--help] [-h] [-s]."
        echo -e "   -h:     Hard reset."
        echo -e "   -s:     Soft reset.\n"
    elif [ "$1" == "-h" ]; then
        git reset --hard
    elif [ "$1" == "-s" ]; then
        git reset --soft HEAD^
    fi
fi