#!/bin/bash

if [ -z "$1" ]; then
    echo "Missing argument for: file name."
	echo "Use --help for more information."
else
    if [ "$1" == "--help" ]; then
        echo -e "\nOpens a file with TextEdit."
        echo -e "\nUsage: ted [--help] <filename>\n"
    else
        open -a TextEdit "$1"
    fi
fi
